apps/account/urls.py
from django.urls import path

from . import views

app_name = 'account'


urlpatterns = [
    path(route='login/', view=views.login_access, name='login_access'),
    path(route='login/confirm/', view=views.login_confirm, name='login_confirm'),
    path(route='register/', view=views.register_access, name='register_access'),
    path(route='register/confirm/', view=views.register_confirm, name='register_confirm'),
    path(route='update/<str:name>/<int:id>/', view=views.update_confirm, name='update_confirm'),
    path(route='logout/', view=views.logout_view, name='logout_view'), 
    path(route='dashboard/<str:name>/<int:id>/', view=views.dashboard, name='dashboard'),
    path(route='dashboard-view/<str:name>/<int:id>/', view=views.dashboard_view, name='dashboard_view'), 
    path(route='members/', view=views.members_all, name='members_all'), 
    path(route='members/staffs/', view=views.members_staffs, name='members_staffs'), 
    path(route='members/topics/', view=views.members_topics, name='members_topics'), 
    path(route='members/replies/', view=views.members_replies, name='members_replies'), 
    path(route='members/likes/', view=views.members_likes, name='members_likes'), 
]

apps/forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'

urlpatterns = [
    path(route='', view=views.home, name='home'),
    path(route='session/<int:session_id>/', view=views.session, name='session'),
    path(route='session/<int:session_id>/topic/<int:topic_id>/', view=views.topic, name='topic'),
    path(route='reply-to/<int:session_id>/topic/<int:topic_id>/', view=views.reply, name='reply'),
    path(route='topic-creation/<int:session_id>/', view=views.topic_creation, name='topic_creation'),
    path(route='topic-create/<int:session_id>/', view=views.topic_confirm, name='topic_confirm'),
    path(route='delete-topic/<int:session_id>/topic/<int:topic_id>/', view=views.topic_delete, name='topic_delete'),
    path(route='delete-reply/<int:session_id>/topic/<int:topic_id>/<int:reply_id>/', view=views.reply_delete, name='reply_delete'),
    path(route='search-tag/<str:tag_name>/<int:tag_id>/', view=views.search_by_tag, name='tag'),
    path(route='search/', view=views.search_list_view, name='query'),
    path(route='like/<int:session_id>/<int:topic_id>/', view=views.like_topic, name='like_topic'),
    path(route='like/<int:session_id>/<int:topic_id>/<int:reply_id>/', view=views.like_reply, name='like_reply'),
]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render
from django.urls import include, path

urlpatterns = [
    path(route='admin/', view=admin.site.urls),
    path(route='', view=include('apps.forum.urls')),
    path(route='', view=include('apps.account.urls')),
    # path(route='', view=include('apps.tag.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/global/content/dashboard-view.html
{% extends 'global/extend/index.html' %}
{% block title %}perfil - {{request.user.username}}{% endblock title %}
{% block content %}
    <div class="dashboard-view-main-container">
        <div class="dashboard-view-header">
            <h1>Perfil de {{member_user.username}}</h1>
        </div>
        <div class="dashboard-view-body">
            <div class="dashboard-view-statistics">
                <span>
                    Estatísticas de {{member_user.username}}:
                    Tópicos: {{member_topics.count}}
                    Mensagens: {{member_replies.count}}
                    Likes: {{total_likes}}
                </span>
                <span>
                    Ingressou em {{member_user.date_joined}}
                </span>
            </div>
            <div class="dashboard-view-topics-started">
                <div>Tópicos:</div>
                {% for topic in member_topics %}
                    <span>
                        <a href="{% url 'forum:topic' session_id=topic.topic_session_id topic_id=topic.id %}">{{topic}}</a>
                    </span>
                {% endfor %}
            </div>
            <div class="dashboard-view-replies">
                <div>Comentários:</div>
                {% comment %} {% for reply in member_replies %} {% endcomment %}
                {% for reply in pagination.0 %}
                    <span>
                        <a href="{% url 'forum:topic' session_id=reply.reply_topic.topic_session_id topic_id=reply.reply_topic_id %}">
                            {{reply.reply_topic}}</a>
                    </span>
                    <span>
                        <a href="{% url 'forum:topic' session_id=reply.reply_topic.topic_session_id topic_id=reply.reply_topic_id %}?page={{reply}}#comment-of-{{reply.reply_user.username}}-{{reply.id}}">
                            {{reply.reply_content}}</a>
                    </span>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}  

templates/global/content/home.html
{% extends 'global/extend/index.html' %}
{% block title %}home{% endblock title %}
{% block content %}
    <div class="home-centralized-box-container">
        <div class="home-page-main-container">
            <div>
                <div class="home-page-topics-container">
                    {% for _, forum in dict_data.items %}
                        <div class="home-page-title-container">
                            <h1>{{forum.0.forum_title}}</h1>
                            {% if forum.0.forum_description %}
                                <blockquote>{{forum.0.forum_description}}</blockquote>
                            {% endif %}
                        </div>
                        <div>
                            <section class="home-page-section-main-container">
                                {% for _, session in forum.1.items %}
                                    <div class="home-page-section-title-container">
                                        <div class="home-page-display-flex">
                                            <div>
                                                <i class="fa-solid fa-folder-open"></i>
                                            </div>
                                            <div>
                                                <h2>
                                                    <a href="{% url 'forum:session' session_id=session.0.id %}">
                                                        {{session.0.session_title}}
                                                    </a>
                                                </h2>
                                                {% if session.0.session_description is not None %}
                                                    <blockquote>{{session.0.session_description}}</blockquote>
                                                {% endif %}
                                            </div>
                                        </div>
                                        <div>
                                            <blockquote>Tópicos: {{session.0.total_topics}} Mensagens: {{session.0.total_replies}}</blockquote>
                                        </div>
                                    </div>
                                    {% if session.1 %}
                                        <ul class="home-page-topic-ul">
                                            {% for topic in session.1|slice:5 %}
                                                <li class="home-page-discussions-main-container">
                                                    <div class="home-page-display-flex">
                                                        <div>
                                                            <span><i class="fa-solid fa-comments"></i></span>
                                                        </div>
                                                        <div class="home-page-messages-counter">
                                                            <h3>
                                                                <a href="{% url 'forum:topic' session_id=session.0.id topic_id=topic.0.id %}">
                                                                    {{topic.0.topic_title}}
                                                                </a>
                                                            </h3>
                                                            <span>
                                                                {% if topic.0.topic_user %}
                                                                <a href="{% url 'account:dashboard_view' name=topic.0.topic_user.username id=topic.0.topic_user.id %}">
                                                                    {{topic.0.topic_user.username}}</a>
                                                                {% else %}
                                                                    usuário_excluído
                                                                {% endif %}, {{topic.0.topic_timestamp_create|date:"d \d\e F \d\e Y"}}
                                                                Mensagens: {{topic.0.total_replies}}
                                                                {% include 'global/include/pagination-home.html' %}
                                                            </span>
                                                        </div>
                                                    </div>
                                                    {% if topic.0.last_reply_id %}
                                                        <div>
                                                            <div class="home-page-most-recent-topic-update">
                                                                <span>Última postagem por
                                                                    {% if topic.0.last_reply_username %}
                                                                        <a href="{% url 'account:dashboard_view' name=topic.0.last_reply_username id=topic.0.last_reply_user_id %}">
                                                                        <strong>{{topic.0.last_reply_username}}</strong>
                                                                        </a>
                                                                    {% else %}
                                                                        <b>usuário_excluído</b>
                                                                    {% endif %}<br>{{topic.0.last_reply_timestamp|date:"d/m/Y à\s H:i:s"}}
                                                                </span>
                                                            </div>
                                                        </div>
                                                    {% endif %}
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}
                                {% endfor %}
                            </section>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div>
                <div class="home-page-statistics-main-container">
                    <div class="home-page-statistics-header">
                        <h2>Mais recentes</h2>
                    </div>
                    <div class="home-page-statistics home-page-feed">
                        <ul>
                            {% for feed in topic_feed %}
                                <li>
                                    <span>
                                        <a href="{% url 'forum:topic' session_id=feed.topic_session_id topic_id=feed.id %}">
                                            {{feed}}</a>{% if not forloop.last %},{% endif %}
                                    </span>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="home-page-statistics-main-container">
                    <div class="home-page-statistics-header">
                        <h2>Estatísticas do Fórum</h2>
                    </div>
                    <div class="home-page-statistics">
                        <dl>
                            <dt>Tópicos:</dt>
                            <dd>{{total.0.topics}}</dd>
                        </dl>
                        <dl>
                            <dt>Mensagens:</dt>
                            <dd>{{total.1.replies}}</dd>
                        </dl>
                        <dl>
                            <dt>Usuários:</dt>
                            <dd>{{total.2.users}}</dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/global/content/login.html
{% extends 'global/extend/index.html' %}
{% block title %}contas - login{% endblock title %}
{% block content %}
    <div class="login-h1">
        <h1>Fazer Login</h1>
    </div>
    <div class="login-form-outter-box-container">
        <form action="{{form_confirmation}}" method="POST">
            {% csrf_token %}
            {% for field in form %}
                <div>
                    {{field.label}}
                    {{field}}
                    {% if field.help_text %}
                        {{field.help_text}}
                    {% endif %}
                    {{field.errors}}
                </div>
            {% endfor %}
            <div class="login-form-button">
                <button type="submit">Confirmar</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/global/content/members.html
{% extends 'global/extend/index.html' %}
{% load static %}
{% block title %}Usuários{% endblock title %}
{% block content %}
    <div>
        <div class="members-main-header">
            <h1>Lista de membros do fórum</h1>
        </div>
        {% include 'global/include/pagination.html' %}
        <div class="members-body-container">
            <nav class="members-nav-container">
                <ul class="members-nav-ul-main-container">
                    <a href="{% url 'account:members_all' %}">
                        <li>Todos</li>
                    </a>
                    <a href="{% url 'account:members_staffs' %}">
                        <li>Moderadores</li>
                    </a>
                    <a href="{% url 'account:members_likes' %}">
                        <li>Likes</li>
                    </a>
                    <a href="{% url 'account:members_topics' %}">
                        <li>Tópicos</li>
                    </a>
                    <a href="{% url 'account:members_replies' %}">
                        <li>Comentários</li>
                    </a>
                </ul>
                <div class="member-list-header">
                    {% if request.path == '/members/likes/' %}
                        <span>Likes</span>
                    {% elif request.path == '/members/replies/' %}
                        <span>Comentários</span>
                    {% else %}
                        <span>Tópicos</span>
                    {% endif %}
                </div>
            </nav>
            <div class="members-list-main-container" id="members-list-filter-a">
                {% for member in members %}
                    <div class="member-list-outer-loop">
                        <div>
                            <div class="member-list-inner-loop">
                                <div class="member-image">
                                    {% if member.account.img %}
                                        <img src="{{member.account.img.url}}" alt="Avatar de {{member.username}}" title="Avatar de {{member.username}}">
                                    {% else %}
                                    <img src="{% static 'img/default/default128x128.png' %}" alt="Avatar de {{member.username}}" title="Avatar de {{member.username}}">
                                    {% endif %}
                                </div>
                                <div class="member-list-inner-infos">
                                    <div class="member-list-inner-is-staff">
                                        <a href="{% url 'account:dashboard_view' name=member.username id=member.id %}">
                                            <strong>{{member.username}}</strong>
                                        </a>
                                        {% if member.is_staff %}
                                            <a href="{% url 'account:members_staffs' %}" class="member-list-inner-is-staff-mod">
                                                Moderador
                                            </a>
                                        {% endif %}
                                    </div>
                                    <div class="member-list-inner-statistics">
                                        <span>{{member.account.gender}}
                                            {% if member.account.birth_date %}
                                                {{member.account.birth_date|date:"d/m/Y"}}
                                            {% else %}
                                            {% endif %}
                                            Mensagens: {{member.total_replies}}
                                            likes: {{member.total_likes}}
                                            Tópicos: {{member.total_topics}}
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="member-list-outer-total">
                            {% if request.path == '/members/likes/' %}
                                <span>{{member.total_likes}}</span>
                            {% elif request.path == '/members/replies/' %}
                                <span>{{member.total_replies}}</span>
                            {% else %}
                                <span>{{member.total_topics}}</span>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        {% include 'global/include/pagination.html' %}
    </div>
{% endblock content %}

templates/global/content/register.html
{% extends 'global/extend/index.html' %}
{% block title %}Cadastro{% endblock title %}
{% block content %}
    {% include 'global/include/messages.html' %}
    <h1 class="form-register-h1">Criar Conta</h1>
        <form
            action="{{form_confirmation}}" 
            method="POST" 
            class="form-register-main-container" 
            enctype="multipart/form-data"
        >
            {% csrf_token %}
            <fieldset class="form-register-content form-register-grid">
                {% include 'global/include/register-user-account-form.html' %}
            </fieldset>
            <div class="form-register-button-submit">
                <button type="submit">Enviar</button>
            </div>
        </form>
{% endblock content %}

templates/global/content/search-by-tag.html
{% extends 'global/extend/index.html' %}
{% block title %}{{tag.tag_name}}{% endblock title %}
{% block content %}
<div>
    <span>Resultado de todos os tópicos com a TAG "<strong>{{tag.1}}</strong>"</span>
</div>
    {% include 'global/include/pagination.html' %}
    <ul class="tag-ul-main-container">
        {% for topic in pagination.0 %}
            <li class="tag-li-container">
                <span>
                    <a href="{% url 'forum:topic' session_id=topic.topic_session_id topic_id=topic.id %}">
                        <strong>{{topic.topic_title}}</strong></a>
                        <br>Criado por
                    {% if topic.topic_user %}
                        <a href="{% url 'account:dashboard_view' name=topic.topic_user id=topic.topic_user.id %}">
                        {{topic.topic_user}}</a> em
                    {% else %}
                        usuário_excluído
                    {% endif %}
                    <a href="{% url 'forum:session' session_id=topic.topic_session_id %}">
                        {{topic.topic_session}}</a>, {{topic.topic_timestamp_create|date:"d \d\e F \d\e Y à\s H:i"}}.
                </span>
            </li>
        {% endfor %}
    </ul>
    {% include 'global/include/pagination.html' %}
{% endblock content %}

templates/global/content/search-list.html
{% extends 'global/extend/index.html' %}
{% block title %}{{query_title}}{% endblock title %}
{% block content %}
    <div>
        <h1>{{total}} resultados para "{{query_title}}"</h1>
    </div>
    {% include 'global/include/pagination.html' %}
    <div class="search-list-main-container">
        {% for topic in pagination.0 %}
            <div class="search-list-grid-row-container search-list-topic-container">
                <div class="search-list-grid-column-container">
                    <div>
                        <span>
                            <a href="{% url 'forum:topic' session_id=topic.topic_session_id topic_id=topic.id %}">
                                <strong>{{topic}}</strong></a> em
                            <a href="{% url 'forum:session' session_id=topic.topic_session.id %}">
                                {{topic.topic_session.session_title}}</a>
                        </span>
                    </div>
                    <div class="search-list-topic-user-container">
                        <span>Tópico criado por
                            {% if topic.topic_user %}
                            <a href="{% url 'account:dashboard_view' name=topic.topic_user.username id=topic.topic_user.id %}">
                                <strong>{{topic.topic_user.username}}</strong></a>
                            {% else %}
                                <b>usuário_excluído</b>
                            {% endif %}, em {{topic.topic_timestamp_create|date:"d \d\e F \d\e Y à\s H:i:s"}}
                        </span>
                    </div>
                </div>
                <div class="search-list-topic-content">
                    {{topic.topic_content|truncatechars:300}}
                </div>
            </div>
        {% endfor %}
    </div>
    {% include 'global/include/pagination.html' %}
{% endblock content %}

templates/global/content/session.html
{% extends 'global/extend/index.html' %}
{% load static %}
{% block title %}{{session.session_title}}{% endblock title %}
{% block content %}
    <div>
        <div class="session-title-main-container">
            <h1>{{session.session_title}}</h1>
            <blockquote>{{session.session_description}}</blockquote>
        </div>
    </div>
    <div class="session-pagination-and-create-topic-container">
        {% include 'global/include/pagination.html' %}
    {% if request.user.is_authenticated and staff_only %}
        {% if request.user.is_staff %}
            <div class="session-link-create-topic">
                <a href="{% url 'forum:topic_creation' session_id=session.id %}">
                    Criar tópico
                </a>
            </div>
        {% endif %}
    {% elif request.user.is_authenticated %}
        <div class="session-link-create-topic">
            <a href="{% url 'forum:topic_creation' session_id=session.id %}">Criar tópico</a>
        </div>
    {% endif %}
    </div>
    <div class="session-topics-main-container">
        <div class="session-topics-header">
            <span></span>
            <span>Comentários</span>
            <span>Visitas</span>
            <span>Última postagem</span>
        </div>
        {% if pagination.0 %}
            {% for topic in pagination.0 %}
            <div class="session-topics-each">
                <div class="session-topic-creator">
                    {% if topic.topic_user %}
                        <a href="{% url 'account:dashboard_view' name=topic.topic_user.username id=topic.topic_user.id %}">
                        {% if topic.topic_user.account.img %}
                                <img
                                    src="{{topic.topic_user.account.img.url}}"
                                    title="Avatar de {{topic.topic_user.username}}"
                                    alt="Avatar de {{topic.topic_user.username}}"
                                >
                        {% else %}
                                <img
                                    src="{% static 'media/img/default/default128x128.png' %}"
                                    title="Usuário excluído"
                                    alt="Usuário excluído"
                                >
                        {% endif %}
                        </a>
                    {% else %}
                        <img
                            src="{% static 'media/img/default/default128x128.png' %}"
                            title="Usuário excluído"
                            alt="Usuário excluído"
                        >
                    {% endif %}
                    <div class="session-topic-creator-header">
                        <div>
                            <h2>
                                <a href="{% url 'forum:topic' session_id=topic.topic_session_id topic_id=topic.id %}">
                                    {{topic.topic_title}}
                                </a>
                            </h2>
                            <span>
                                {% if topic.topic_user %}
                                <a href="{% url 'account:dashboard_view' name=topic.topic_user.username id=topic.topic_user_id %}">
                                    {{topic.topic_user.username}}</a>
                                {% else %}
                                    usuário_excluído
                                {% endif %}, {{topic.topic_timestamp_create|date:"d \d\e F \d\e Y à\s H:i:s"}}
                            </span>
                        </div>
                    </div>
                </div>
                <div class="session-topic-creator-content session-topic-creator-content-last-user">
                    <span>{{topic.reply_count}}</span>
                </div>
                <div class="session-topic-creator-content session-topic-creator-content-last-user">
                    <span>{{topic.views}}</span>
                </div>
                <div class="session-topic-creator-content">
                    {% if topic.last_reply_username %}
                        <span>
                            <a href="{% url 'account:dashboard_view' name=topic.last_reply_username id=topic.last_reply_id %}">
                                {{topic.last_reply_username}}</a>, {{topic.last_reply_timestamp}}
                        </span>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="session-topics-each">
            <span>Crie o primeiro tópico!</span>
        </div>
    {% endif %}
    </div>
    {% include 'global/include/pagination.html' %}
{% endblock content %}

templates/global/content/topic-creation.html
{% extends 'global/extend/index.html' %}
{% block title %}criação de tópico{% endblock title %}
{% block content %}
    <div class="topic-creation-header">
        <h1>Tópico em: "<a href="{% url 'forum:session' session_id=session_id %}">{{session.session_title}}</a>"</h1>
    </div>
    <div class="topic-creation-main-container topic-creation-grid">
        <form action="{{form_confirmation}}" method="POST">
            {% csrf_token %}
            {% for field in form %}
                <div>
                    {% if field.name == 'fixed' and not request.user.is_staff %}
                        <!--SKIP-->
                    {% else %}
                        <label>{{field.label}}</label>
                        {{field}}
                        {% if field.help_text %}
                            <span class="topic-creation-help-text">{{field.help_text}}</span>
                        {% endif %}
                        {{field.errors}}
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <span><i class="fa-solid fa-triangle-exclamation"></i>{{error}}</span>
                            {% endfor %}
                        {% endif %}
                    {% endif %}
                </div>
            {% endfor %}
            <button class="topic-creation-button">Criar Tópico</button>
        </form>
    </div>
{% endblock content %}

templates/global/content/topic.html
{% extends 'global/extend/index.html' %}
{% block title %}discussão - {{topic.topic_title}}{% endblock title %}
{% block content %}
    <div>
        <div class="topic-title-main-container">
            <div>
                <h1>
                    {{topic.topic_title}}
                </h1>
            </div>
            <blockquote>
                Discussão em 
                <a href="{% url 'forum:session' session_id=topic.topic_session_id %}">{{topic.topic_session.session_title}}</a>
                iniciado por 
                {% if topic.topic_user %}
                <a href="{% url 'account:dashboard_view' name=topic.topic_user.username id=topic.topic_user_id %}">
                    {{topic.topic_user.username}}</a>
                {% else %}
                    <b>usuário_excluído</b>
                {% endif %}, em {{topic.topic_timestamp_create|date:"d \d\e F \d\e Y à\s H:i:s"}}
            </blockquote>
            <div>
                {% include 'global/include/pagination.html' %}
            </div>
        </div>
        <div class="topic-comment-section-container">
            {% include 'global/include/topics.html' %}
            {% if pagination.0 %}
                Comentários: <hr>
            {% endif %}
            {% include 'global/include/replies.html' %}
        </div>
        <div>
            {% include 'global/include/pagination.html' %}
        </div>
        {% include 'global/include/reply.html' %}
    </div>
    {% comment %} {% include 'global/include/reply-delete-confirmation.html' %} {% endcomment %}
{% endblock content %}