apps/account/urls.py
from django.urls import path

from . import views

app_name = 'account'


urlpatterns = [
    path(route='login/', view=views.login_access, name='login_access'),
    path(route='login/confirm/', view=views.login_confirm, name='login_confirm'),
    path(route='register/', view=views.register_access, name='register_access'),
    path(route='register/confirm/', view=views.register_confirm, name='register_confirm'),
    path(route='update/<str:name>/<int:id>/', view=views.update_confirm, name='update_confirm'),
    path(route='logout/', view=views.logout_view, name='logout_view'), 
    path(route='dashboard/<str:name>/<int:id>/', view=views.dashboard, name='dashboard'),
    path(route='dashboard-view/<str:name>/<int:id>/', view=views.dashboard_view, name='dashboard_view'), 
    path(route='members/', view=views.members_all, name='members_all'), 
    path(route='members/staffs/', view=views.members_staffs, name='members_staffs'), 
    path(route='members/topics/', view=views.members_topics, name='members_topics'), 
    path(route='members/replies/', view=views.members_replies, name='members_replies'), 
    path(route='members/likes/', view=views.members_likes, name='members_likes'), 
]

apps/forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'

urlpatterns = [
    path(route='', view=views.home, name='home'),
    path(route='session/<int:session_id>/', view=views.session, name='session'),
    path(route='session/<int:session_id>/topic/<int:topic_id>/', view=views.topic, name='topic'),
    path(route='reply-to/<int:session_id>/topic/<int:topic_id>/', view=views.reply, name='reply'),
    path(route='topic-creation/<int:session_id>/', view=views.topic_creation, name='topic_creation'),
    path(route='topic-create/<int:session_id>/', view=views.topic_confirm, name='topic_confirm'),
    path(route='delete-topic/<int:session_id>/topic/<int:topic_id>/', view=views.topic_delete, name='topic_delete'),
    path(route='delete-reply/<int:session_id>/topic/<int:topic_id>/<int:reply_id>/', view=views.reply_delete, name='reply_delete'),
    path(route='search-tag/<str:tag_name>/<int:tag_id>/', view=views.search_by_tag, name='tag'),
    path(route='search/', view=views.search_list_view, name='query'),
    path(route='like/<int:session_id>/<int:topic_id>/', view=views.like_topic, name='like_topic'),
    path(route='like/<int:session_id>/<int:topic_id>/<int:reply_id>/', view=views.like_reply, name='like_reply'),
]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render
from django.urls import include, path

urlpatterns = [
    path(route='admin/', view=admin.site.urls),
    path(route='', view=include('apps.forum.urls')),
    path(route='', view=include('apps.account.urls')),
    # path(route='', view=include('apps.tag.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/global/include/breadcrumb.html
<div class="breadcrumb-main-container">
    <div>
        <i class="fa-solid fa-house"></i>
    </div>
    <ol class="breadcrumb-ordered-nav-list">
        <li>
            <span>
                <a href="{% url 'forum:home' %}">Home</a>
            </span>
        </li>
        {% for link in breadcrumb %}
            <li>
                <span>
                    {% if forloop.counter == 2 %}
                        <a href="{% url 'forum:topic' session_id=link.topic_session_id topic_id=link.id %}">
                    {% else %}
                        <a href="{% url 'forum:session' session_id=link.id %}">
                    {% endif %}
                        {{link}}
                    </a>
                </span>
            </li>
        {% endfor %}
    </ol>
</div>

templates/global/include/dashboard-nav.html
<nav class="dashboard-nav-bar">
    <ul class="dashboard-nav-boxes">
        <li>
            <div class="dashboard-nav-profile-buttons js-button-highlight-on" id="dashboard-nav-button-a">
                <button title="Início" id="dashboard-button-a">
                    <i class="fa-solid fa-house"></i>
                </button>
            </div>
        </li>
        <li>
            <div class="dashboard-nav-profile-buttons js-button-highlight-off" id="dashboard-nav-button-b">
                <button title="Meus dados" id="dashboard-button-b">
                    <i class="fa-solid fa-address-card"></i>
                </button>
            </div>
        </li>
        <li>
            <div class="dashboard-nav-profile-buttons js-button-highlight-off" id="dashboard-nav-button-c">
                <button title="Meus comentários" id="dashboard-button-c">
                    <i class="fa-solid fa-comments"></i>
                </button>
            </div>
        </li>
    </ul>
</nav>

templates/global/include/edit-reply.html
<div class="edit-reply-main-container">
    
</div>

templates/global/include/footer.html
<div>
    <div class="footer-upper-container">
        <div class="footer-centralized-box-container">
            <ul class="footer-upper-ul-style">
                <li>
                    <a href="/" title="Entre em contato">
                        <i class="fa-solid fa-envelope"></i>
                    </a>
                </li>
                <li>
                    <a href="https://www.instagram.com/" target="_blank" title="Instagram">
                        <i class="fa-brands fa-square-instagram"></i>
                    </a>
                </li>
                <li>
                    <a href="https://twitter.com/" target="_blank" title="Twitter">
                        <i class="fa-brands fa-twitter"></i>
                    </a>
                </li>
                <li>
                    <a href="https://www.youtube.com/" target="_blank" title="YouTube">
                        <i class="fa-brands fa-youtube"></i>
                    </a>
                </li>
                <li>
                    <a href="https://br.linkedin.com/" target="_blank" title="LinkedIn">
                        <i class="fa-brands fa-linkedin"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="footer-lower-container">
        <div class="footer-centralized-box-container">
            <div class="footer-lower-style">
                <span>
                    Criado por <strong>Ciro Torres</strong>. Powered by <b>Django</b>.
                </span>
            </div>
        </div>
    </div>
</div>

templates/global/include/go-back.html
<a href="{{request.META.HTTP_REFERER|escape}}">
    <div class="session-go-back-link">
        <span>
            <i class="fa-solid fa-circle-arrow-left"></i>
            Voltar
        </span>
    </div>
</a>

templates/global/include/header.html
<!-- 
    Células com 'width' fixas:
    https://codepen.io/adamgonzls/pen/BKdVZd
 -->
<nav class="header-display-grid">
    <div class="header-nav-vertical-margin header-fit-content">
        {% if request.user.is_authenticated %}
            <form action="{% url 'account:logout_view' %}" method="POST" class="header-form">
                {% csrf_token %}
                Olá
                <a 
                    href="{% url 'account:dashboard' name=user.username id=user.id %}" 
                    class="header-form-username" 
                    title="Perfil">{{request.user.username}}</a> |
                <button type="submit">sair</button>
                <input type="hidden" name="username" value="{{request.user.username}}"><!--NECESSÁRIO!-->
            </form>
        {% else %}
            <ul class="header-ul-display-flex-inline header-ul-menu-selection-style">
                <li><a href="{% url 'account:login_access' %}">Entrar</a></li>
                <li><a href="{% url 'account:register_access' %}">Cadastrar</a></li>
            </ul>
        {% endif %}
    </div class="header-nav-vertical-margin">
    <div class="header-search-bar-fit-content">
        {% include 'global/include/search.html' %}
    </div>
    <div class="header-nav-right-side-aligned-by-margin header-fit-content">
        <ul class="header-ul-display-flex-inline header-ul-menu-selection-style">
            <li><a href="{% url 'forum:home' %}">Home</a></li>
            <li><a href="{% url 'account:members_all' %}">Membros</a></li>
        </ul>
    </div>
</nav>

templates/global/include/like_topic_thumbs_up.html
{% if request.user.is_authenticated %}
    <div class="topic-like">
        <form action="{% url 'forum:like_topic' session_id=topic.topic_session_id topic_id=topic.id %}" method="POST">
            {% csrf_token %}
            {% if request.user in topic.likes.all %}
                <button type="submit" name="topic_id" value="{{topic.id}}" class="button-like">
                    <i class="fa-solid fa-thumbs-up"></i>
                </button>
            {% else %}
                <button type="submit" name="topic_id" value="{{topic.id}}" class="button-dislike">
                    <i class="fa-solid fa-thumbs-up"></i>
                </button>
            {% endif %}
        </form>
    </div>
{% endif %}

templates/global/include/likes_users.html
{% if likes.0 %}
    <div class="topic-like-main-section">
        <span class="topic-like-ul">
            {% for like in likes.0|slice:10 %}
                <a href="{% url 'account:dashboard_view' name=like.username id=like.id %}" class="topic-footer-like-user-link">
                    <span>
                        <b>{{like.username}}</b>
                    </span>
                </a>
                {% if forloop.revcounter0 > 1 %}
                    ,
                {% elif forloop.revcounter0 == 1 %}
                    e
                {% endif %}
                {% if forloop.last %}
                    {% if forloop.counter == 1 %}
                        curtiu isso
                    {% elif forloop.counter > 1 %}
                        {% if likes.0.count > 10 %}  <!--ESSE IF NUNCA FOI TESTADO-->
                            e mais {{likes.0.count|add:"-10"}} curtiram isso
                        {% else %}
                            curtiram isso
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endfor %}
        </span>
    </div>
    <div class="topic-like-total">
        <span>Ao todo {{likes.1}} {% if likes.1 > 1 %}pessoas curtiram{% else %}pessoa curtiu{% endif %} esse tópico</span>
    </div>
{% endif %}

templates/global/include/pagination-home.html
{% if topic.1.0.has_other_pages %}
    <nav class="home-pagination">
        Páginas:
        {% if topic.1.4 > 2 %}
            <a href="{% url 'forum:topic' session_id=session.0.id topic_id=topic.0.id %}?page={{topic.1.4|add:-2}}">
                {{topic.1.4|add:-2}}
            </a>
        {% endif %}
        {% if topic.1.4 > 1 %}
            <a href="{% url 'forum:topic' session_id=session.0.id topic_id=topic.0.id %}?page={{topic.1.4|add:-1}}">
                {{topic.1.4|add:-1}}
            </a>
        {% endif %}
        <a href="{% url 'forum:topic' session_id=session.0.id topic_id=topic.0.id %}?page={{topic.1.4}}">
            {{topic.1.4}}
        </a>
    </nav>
{% endif %}

templates/global/include/pagination.html
{% if pagination.0.has_other_pages %}
    <nav class="pagination">
        Página {{pagination.5}} de {{pagination.4}}
        {% if pagination.3 %}
            <div class="pagination-width-aligned-cells pagination-pages">
                <a href="?{% if query %}q={{query}}&{% endif %}page={{pagination.0.previous_page_number}}">
                    <div class="pagination-width-aligned-cells">
                        <span><i class="fa-solid fa-chevron-left"></i></span>
                    </div>
                </a>
            </div>
        {% else %}
        <div class="pagination-width-aligned-cells">
            <div class="pagination-width-aligned-cells">
                
            </div>
        </div>
        {% endif %}
        {% if pagination.5 == 1 %}
            <div class="pagination-width-aligned-cells pagination-pages pagination-current-page">
                <a href="?{% if query %}q={{query}}&{% endif %}page=1">
                    <div class="pagination-width-aligned-cells">
                        <span>1</span>
                    </div>
                </a>
            </div>
        {% else %}
            <div class="pagination-width-aligned-cells pagination-pages">
                <a href="?{% if query %}q={{query}}&{% endif %}page=1">
                    <div class="pagination-width-aligned-cells">
                        <span>1</span>
                    </div>
                </a>
            </div>
        {% endif %}
        {% if pagination.0.number|add:"-2" > 2 %}
            <div class="pagination-width-aligned-cells">
                <div class="pagination-width-aligned-cells">
                    <span>&hellip;</span>
                </div>
            </div>
        {% endif %}
        {% for page in pagination.1 %}
            {% if page == 1 %}
                <!--primeira página é fixa-->
            {% elif page == pagination.4 %}
                <!--última página é fixa-->
            {% elif page == pagination.0.number %}
                {% if page == pagination.5 %}
                    <div class="pagination-width-aligned-cells pagination-pages pagination-current-page">
                        <a href="?{% if query %}q={{query}}&{% endif %}page={{pagination.0.number}}">
                            <div class="pagination-width-aligned-cells">
                                <span>{{pagination.0.number}}</span>
                            </div>
                        </a>
                    </div>
                {% else %}
                    <div class="pagination-width-aligned-cells pagination-pages">
                        <a href="?{% if query %}q={{query}}&{% endif %}page={{pagination.0.number}}">
                            <div class="pagination-width-aligned-cells">
                                <span>{{pagination.0.number}}</span>
                            </div>
                        </a>
                    </div>
                {% endif %}
            {% elif page > pagination.0.number|add:"-3" and page < pagination.0.number|add:"3" %}
                <div class="pagination-width-aligned-cells pagination-pages">
                    <a href="?{% if query %}q={{query}}&{% endif %}page={{page}}">
                        <div class="pagination-width-aligned-cells">
                            <span>{{page}}</span>
                        </div>
                    </a>
                </div>
            {% endif %}
        {% endfor %}
        {% if pagination.4 > pagination.0.number|add:"3" %}
            <div class="pagination-width-aligned-cells">
                <div class="pagination-width-aligned-cells">
                    <span>&hellip;</span>
                </div>
            </div>
        {% endif %}
        {% if pagination.4 %}
            {% if pagination.5 == pagination.4 %}
                <div class="pagination-width-aligned-cells pagination-pages pagination-current-page">
                    <a href="?{% if query %}q={{query}}&{% endif %}page={{pagination.4}}">
                        <div class="pagination-width-aligned-cells">
                            <span>{{pagination.4}}</span>
                        </div>
                    </a>
                </div>
            {% else %}
                <div class="pagination-width-aligned-cells pagination-pages">
                    <a href="?{% if query %}q={{query}}&{% endif %}page={{pagination.4}}">
                        <div class="pagination-width-aligned-cells">
                            <span>{{pagination.4}}</span>
                        </div>
                    </a>
                </div>
            {% endif %}
        {% endif %}
        {% if pagination.2 %}
            <div class="pagination-width-aligned-cells pagination-pages">
                <a href="?{% if query %}q={{query}}&{% endif %}page={{pagination.0.next_page_number}}">
                    <div class="pagination-width-aligned-cells">
                        <i class="fa-solid fa-chevron-right"></i>
                    </div>
                </a>
            </div>
        {% else %}
            <div class="pagination-width-aligned-cells">
                <div class="pagination-width-aligned-cells">
                    
                </div>
            </div>
        {% endif %}
    </nav>
{% endif %}

templates/global/include/register-user-account-form.html
{% for user_field in user_form %}
    {% if user_field.name == 'password' %}
        <div class="form-account-outer-content">
            {% for account_field in account_form %}
                <div class="form-account-inner-content">
                    {% if account_field.label %}
                        <label for="{{account_field.id_for_label}}">
                            {{account_field.label}}
                            {% if account_field.field.required %}
                                <span class="form-register-required-true">*</span>
                            {% endif %}
                        </label>
                    {% endif %}
                        {{account_field}}
                    {% if account_field.help_text %}
                        <span class="form-help-text">
                            {{account_field.help_text}}
                        </span>
                    {% endif %}
                    {% if account_field.errors %}
                        {% for error in account_field.errors %}
                            <span class="form-error-list"><i class="fa-solid fa-triangle-exclamation"></i> {{error}}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    {% endif %}
    <div class="form-user-outer-content">
        <div class="form-user-inner-content">
            {% if user_field.label %}
                <label for="{{user_field.id_for_label}}">
                    {{user_field.label}}
                    {% if user_field.field.required %}
                        <span class="form-register-required-true">*</span>
                    {% endif %}
                </label>
            {% endif %}
            {{user_field}}
            {% if user_field.help_text %}
                <span class="form-help-text">{{user_field.help_text}}</span>
            {% endif %}
            {% if user_field.errors %}
                {% for error in user_field.errors %}
                    <span class="form-error-list"><i class="fa-solid fa-triangle-exclamation"></i> {{error}}</span>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endfor %}

templates/global/include/reply-delete-confirmation.html
<div class="reply-delete-outer-container">
    <div class="reply-delete-middle-container">
        <div class="reply-delete-inner-container">
            <span>Você tem certeza de que gostaria de <b>DELETAR</b> este comentário? Essa é uma operação sem volta!</span>
            <ul class="reply-delete-ul">
                <li class="reply-delete-li"><a href="">Sim</a></li>
                <li class="reply-delete-li"><a href="">Não</a></li>
            </ul>
        </div>
    </div>
</div>

templates/global/include/topic_update.html
{% if topic.topic_user_id == request.user.id %}
    <div class="topic-outer-discussion-reply-footer">
        <div class="topic-outer-discussion-button">
            <form action="">
                <button>Editar</button>
            </form>
            {% if request.user.is_staff %}
                <form action="{% url 'forum:topic_delete' session_id=topic.topic_session_id topic_id=topic.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" value="comment_{{topic.id}}">Excluir</button>
                </form>
            {% endif %}
        </div>
    </div>
{% elif topic.topic_user_id != request.user.id and request.user.is_staff %}
    <div class="topic-outer-discussion-reply-footer">
        <div class="topic-outer-discussion-button-staff">
            <form action="">
                <button>Editar</button>
            </form>
            {% if request.user.is_staff %}
                <form action="{% url 'forum:topic_delete' session_id=topic.topic_session_id topic_id=topic.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" value="comment_{{topic.id}}">Excluir</button>
                </form>
            {% endif %}
        </div>
    </div>
{% endif %}

templates/global/include/topics.html
{% load static %}
{% if topic.topic_user.is_staff %}
<div class="topic-outer-border topic-outer-border-staff">
{% else %}
<div class="topic-outer-border topic-outer-border-regular">
{% endif %}
    <div class="topic-outer-user-container">
        <div class="topic-inner-left-container topic-inner-left-grid">
            <div class="topic-inner-left-container-img-topics">
                {% if topic.topic_user %}
                    <a href="{% url 'account:dashboard_view' name=topic.topic_user.username id=topic.topic_user_id %}">
                        {% if topic.topic_user.account.img.url is not None %}
                            <img 
                                src="{{topic.topic_user.account.img.url}}" 
                                alt="Avatar de {{topic.topic_user.username}}" 
                                title="Perfil de {{topic.topic_user.username}}"
                            >
                        {% else %}
                            <img 
                                src="{% static 'media/img/default/default128x128.png' %}" 
                                alt="Avatar de {{topic.topic_user.username}}" 
                                title="Perfil de {{topic.topic_user.username}}"
                            >
                        {% endif %}
                    </a>
                    {% else %}
                        <img 
                            src="{% static 'media/img/default/default128x128.png' %}" 
                            alt="Avatar de {{topic.topic_user.username}}" 
                            title="Perfil de {{topic.topic_user.username}}"
                        >
                {% endif %}
            </div>
            <div class="topic-inner-left-container-user-data">
                <span>
                    {% if topic.topic_user %}
                        <a href="{% url 'account:dashboard_view' name=topic.topic_user.username id=topic.topic_user_id %}">
                            {{topic.topic_user.username}}
                        </a>
                </span>
                {% if topic.topic_user.is_staff %}
                    <span class="topic-inner-left-moderator">Moderador</span>
                {% endif %}
                <span>Ingressou: {{topic.topic_user.date_joined|date:"d/m/Y"}}</span>
                <span>
                    {% if topic.topic_user.account.city %}{{topic.topic_user.account.city}}/{% endif %}{{topic.topic_user.account.state}}
                </span>
                {% else %}
                    usuário_excluído
                {% endif %}
            </div>
        </div>
        <div class="topic-inner-right-container">
            <article>
                {{topic.topic_content}}
            </article>
            {% include 'global/include/like_topic_thumbs_up.html' %}
            <div class="topic-footer">
                {% if topic.topic_timestamp_update > topic.topic_timestamp_create %}
                    <div class="topic-footer-creator-info">
                        <span><b>Editado</b> pela última vez por
                            {% if topic.topic_user %}
                            <a href="{% url 'account:dashboard_view' name=topic.topic_user.username id=topic.topic_user.id %}">
                                <strong>{{topic.topic_user.username}}</strong></a>
                            {% else %}
                                <b>usuário_excluído</b>
                            {% endif %}
                            em {{topic.topic_timestamp_update|date:"d \d\e F \d\e Y à\s H:s:i"}}</span>
                    </div>
                {% endif %}
                {% include 'global/include/likes_users.html' %}
                {% if tags %}
                    <div class="topic-tags-main-container">
                        <ul class="topic-tags">
                            {% for tag in tags %}
                                <li>
                                    <a href="{% url 'forum:tag' tag_name=tag.tag__name tag_id=tag.tag %}">
                                        <div class="topics-tag-style">
                                            <span class="topics-tag-style-span">{{tag.tag__name}}</span>
                                        </div>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                <span class="topic-counter">#1</span>
            </div>
        </div>
    </div>
</div>
{% include 'global/include/topic_update.html' %}